In [3]:
import numpy as np
from numpy.linalg import norm
import copy
import os

In [4]:
def relu(x):
    return x*(np.sign(x)+1.)/2.

In [5]:
def sigmoid(x):
    return 1./(1.+np.exp(-x))

In [6]:
def softmax(x):
    return np.exp(x)/sum(np.exp(x))

In [7]:
def mynorm(Z):
    return np.sqrt(np.mean(Z**2))

In [8]:
# Define a three layer feed-forward network

In [9]:
def myANN(Y,Xtrain,Xpred,W01,W02,W03,b01,b02,b03):
    W1 = copy.copy(W01)
    W2 = copy.copy(W02)
    W3 = copy.copy(W03)
    b1 = copy.copy(b01)
    b2 = copy.copy(b02)
    b3 = copy.copy(b03)
    
    k = 1
    change = 999
    
    while(change>0.001 and k<201):
        print("Iteration",k)
        
        Z1 = sigmoid(W1 @ Xtrain + b1)
        Z2 = sigmoid(W2 @ Z1+ b2)
        Yhat = softmax(W3 @ Z2 + b3)
        loss = -Y @ np.log(Yhat)
        print("Current Loss:",loss)
        
        dLdb3 = Yhat - Y 
        dLdW3 = np.outer(dLdb3, Z2)
        # Hidden Layer 2
        dLdb2 = (W3.T @ (dLdb3)) * Z2 * (1-Z2)
        dLdW2 = np.outer(dLdb2,Z1)
        # Hidden Layer 1
        dLdb1 = (W2.T @ (dLdb2)) * Z1 * (1-Z1)
        dLdW1 = np.outer(dLdb1, Xtrain)
        
        b3 = b3 - dLdb3
        W3 = W3 - dLdW3
        b2 = b2 - dLdb2
        W2 = W2 - dLdW2
        b1 = b1 - dLdb1
        W1 = W1 - dLdW1
        
        change = norm(dLdb1)+norm(dLdb2)+norm(dLdb3)+norm(dLdW1)+norm(dLdW2)+norm(dLdW3)
        k = k + 1 
    
    Z1pred = W1 @ Xpred + b1
    Z2pred = W2 @ sigmoid(Z1pred) + b2
    Z3pred = W3 @ sigmoid(Z2pred) + b3
    Ypred = softmax(Z3pred)
    print("")
    print("Summary")
    print("Target Y \n", Y)
    print("Fitted Ytrain \n", Yhat)
    print("Xpred\n", Xpred)
    print("Fitted Ypred \n", Ypred)
    print("Weight Matrix 1 \n", W1)
    print("Bias Vector 1 \n", b1)
    print("Weight Matrix 2 \n", W2)
    print("Bias Vector 2 \n", b2)
    print("Weight Matrix 3 \n", W3)
    print("Bias Vector 3 \n", b3)

In [10]:
# Initial 
W0_1 = np.array([[0.1,0.3,0.7], [0.9,0.4,0.4]])
b_1 = np.array([1.,1.])

W0_2 = np.array([[0.4,0.3], [0.7,0.2]])
b_2 = np.array([1.,1.])

W0_3 = np.array([[0.5,0.6], [0.6,0.7], [0.3,0.2]])
b_3 = np.array([1.,1.,1.]) 

In [11]:
X_train = np.array([0.1,0.7,0.3])
YY = np.array([1.,0.,0.])
X_pred = X_train

In [12]:
myANN(YY, X_train, X_pred, W0_1, W0_2, W0_3, b_1, b_2, b_3)

Iteration 1
Current Loss: 1.0245882244632154
Iteration 2
Current Loss: 0.15485530792507038
Iteration 3
Current Loss: 0.09392421885330306
Iteration 4
Current Loss: 0.06800390179198364
Iteration 5
Current Loss: 0.05342702439392962
Iteration 6
Current Loss: 0.04403516135363163
Iteration 7
Current Loss: 0.037464385843672066
Iteration 8
Current Loss: 0.03260386527878382
Iteration 9
Current Loss: 0.02886032281105674
Iteration 10
Current Loss: 0.025887274175115597
Iteration 11
Current Loss: 0.023468486741688343
Iteration 12
Current Loss: 0.021461901907750262
Iteration 13
Current Loss: 0.019770281829020363
Iteration 14
Current Loss: 0.01832479491681583
Iteration 15
Current Loss: 0.017075333031958018
Iteration 16
Current Loss: 0.0159845417596331
Iteration 17
Current Loss: 0.015024000543215876
Iteration 18
Current Loss: 0.014171699633555721
Iteration 19
Current Loss: 0.013410327234309708
Iteration 20
Current Loss: 0.012726078464642231
Iteration 21
Current Loss: 0.012107809483423326
Iteration 22


In [13]:
# using KERAS
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

In [14]:
# add the layer
model = Sequential()
model.add(Dense(2, input_dim=3, activation='sigmoid', weights = [W0_1.T, b_1]))
model.add(Dense(2, activation='sigmoid', weights = [W0_2.T, b_2]))
model.add(Dense(3, activation='softmax', weights = [W0_3.T, b_3]))

In [15]:
sgd = SGD(lr=1)
model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['categorical_crossentropy'])
model.get_weights()

C:\Users\H\miniconda3\envs\pythonStu\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


[array([[0.1, 0.9],
        [0.3, 0.4],
        [0.7, 0.4]], dtype=float32),
 array([1., 1.], dtype=float32),
 array([[0.4, 0.7],
        [0.3, 0.2]], dtype=float32),
 array([1., 1.], dtype=float32),
 array([[0.5, 0.6, 0.3],
        [0.6, 0.7, 0.2]], dtype=float32),
 array([1., 1., 1.], dtype=float32)]

In [16]:
model.fit(X_train.reshape((1,3)), YY.reshape((1, 3)), epochs=200, batch_size=1)

Epoch 1/200
1/1 [==============================] - 1s 1s/step - loss: 1.0246 - categorical_crossentropy: 1.0246
Epoch 2/200
1/1 [==============================] - 0s 5ms/step - loss: 0.1549 - categorical_crossentropy: 0.1549
Epoch 3/200
1/1 [==============================] - 0s 8ms/step - loss: 0.0939 - categorical_crossentropy: 0.0939
Epoch 4/200
1/1 [==============================] - 0s 5ms/step - loss: 0.0680 - categorical_crossentropy: 0.0680
Epoch 5/200
1/1 [==============================] - 0s 5ms/step - loss: 0.0534 - categorical_crossentropy: 0.0534
Epoch 6/200
1/1 [==============================] - 0s 6ms/step - loss: 0.0440 - categorical_crossentropy: 0.0440
Epoch 7/200
1/1 [==============================] - 0s 5ms/step - loss: 0.0375 - categorical_crossentropy: 0.0375
Epoch 8/200
1/1 [==============================] - 0s 6ms/step - loss: 0.0326 - categorical_crossentropy: 0.0326
Epoch 9/200
1/1 [==============================] - 0s 7ms/step - loss: 0.0289 - categorical_cross

In [17]:
model.predict(X_pred.reshape((1, 3)))

array([[9.9878985e-01, 6.1903609e-04, 5.9115869e-04]], dtype=float32)

In [18]:
model.get_weights()

[array([[0.10459033, 0.9023976 ],
        [0.33213237, 0.41678518],
        [0.7137712 , 0.4071937 ]], dtype=float32),
 array([1.0459025, 1.0239786], dtype=float32),
 array([[0.5922062 , 0.88894045],
        [0.49371308, 0.39044544]], dtype=float32),
 array([1.2366259, 1.2326592], dtype=float32),
 array([[ 2.1052914 , -0.31430355, -0.3909867 ],
        [ 2.2433093 , -0.23618647, -0.5071224 ]], dtype=float32),
 array([ 2.8937364 , -0.08099043,  0.18725535], dtype=float32)]